# Generated by Django 4.1.4 on 2022-12-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Seasonal', 'Seasonal'), ('Single', 'Single')], max_length=10),
        ),
    ]
